### ISSUE TITLE
Should we store voiceTime with channelid?

### ISSUE THREAD

**Issue by Lebyy** [Lebyy/discord-voice#1]
I was thinking of something like { channelid: voicetimeinms, 2ndchannelid: voicetimeinms }

**Comment by SkyDonald** [comment]
Yes its a good idea !

**Comment by Lebyy** [comment]
Alright

**Comment by Lebyy** [comment]
Might work on this aswell in the 1.0.3 release.

**Comment by Lebyy** [comment]
Support added in #9!
