### ISSUE TITLE
error with command voice-leaderboard  

### ISSUE THREAD

**Issue by levarar** [Lebyy/discord-voice#10]
![DeepinScreenshot_выберите-область_20210404194347](https://user-images.githubusercontent.com/68510813/113515601-2559eb80-957e-11eb-8f43-c4f2a03e06ce.png)
Also, if the bot works for a long time, for example, more than an hour, then commands related to the voice are processed for a long time.

**Comment by Lebyy** [comment]
So sorry for late reply! It will be fixed in the next release 1.0.3
