### ISSUE TITLE
blacklist channel + minimal count user

### ISSUE THREAD

**Issue by levarar** [Lebyy/discord-voice#5]
Greetings, if not difficult, please add such functions, the ability to add channels where the system will not read online and the ability to specify the minimum number of users in voice channels to get started.

**Comment by Lebyy** [comment]
I can do that in the next release.

**Comment by Lebyy** [comment]
I am thinking that the user can provide the blacklist channel as an array.
Something like `Voice.setBlacklist(["Id-Here","ID-Here"])`
And for the start part I can make use of the array.includes() function.
👍
And for the users in the voice channel I'll add a param to the start function :)
